### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hara-yuto** [hara-yuto/furima-34762#9]
■自身のフリマアプリのURL 
https://furima-34762-34762.herokuapp.com/

■Basic認証のIDとパスワード 
ID:admin      /      PW:2222

■出品者用のメールアドレスとパスワード 
email: hara@aa      /      PW:yuchan69
■購入者用のメールアドレスとパスワード 
email: yuto@aa     /       PW:yuchan69

**Comment by naru6117** [comment]
@hara-yuto さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [x] **ログイン状態の出品者のみ、出品した商品の商品情報編集ページに遷移できるようにしましょう！**
現状、「商品の編集」ボタンを押しても編集ページに遷移できません。
- [x] **ログイン状態の出品者のみ、出品した商品情報を削除できるようにしましょう！**
現状、削除ボタンを押しても削除ができません。

**※上記のため、その他の項目は次回以降改めて確認いたします！**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
@hara-yuto さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の項目はしっかり修正されていました(^^)
**下記1点のみ確認できていないため、お手数ですが再度データベースをリセットしていただき、ご提出をお願いいたします！**

[今回未確認の項目]

- [x] **商品が出品されていない状態では、ダミーの商品情報が表示されること**

データベースのリセットができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
@hara-yuto さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

![最終課題終了_おめでとう画像3](https://user-images.githubusercontent.com/49669977/112929055-aebe8780-9152-11eb-8aea-36d7f5c68f92.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**Comment by hara-yuto** [comment]
有難うございます！
達成感でいっぱいです！
追加実装やアプリ作成も頑張ります！
